### ISSUE TITLE
Clarification listInvoices on params; limit does not seem to be working

### ISSUE THREAD

**Issue by geoffdutton** [recurly/recurly-client-node#105] opened 2020-04-21 16:40 UTC
I've got a few questions about the [listInvoices](https://recurly.github.io/recurly-client-node/#clientlistinvoices) method.

Per the docs, if I pass `options.params.limit = 20`, I would expect the 20 records back:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
const options = {
  params: {
    limit: 20
  }
}
const invoicePager = await client.listInvoices(options)
console.log('Pager count:', await invoicePager.count())
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  if (total > 20) {
    console.log('Over the limit of 20: ' + total)
    break
  }
}
```

Which outputs:
```
recurly v3.6.0
Pager count: null
Over the limit of 20: 21
```

If I pass `params.limit = 20`, I would expect it not work, but strangely the Pager count is null:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
const params = {
  limit: 20
}
const invoicePager = await client.listInvoices(params)
console.log('Pager count:', await invoicePager.count())
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  if (total > 20) {
    console.log('Over the limit of 20: ' + total)
    break
  }
}
```

Which outputs:
```
recurly v3.6.0
Pager count: 1812
Over the limit of 20: 21
```

If I use `options.params.beginTime`, Pager.count() recognizes it, but it still keep returning:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
// In our sandbox account, we have 8 invoices that fit this criteria
const params = {
  beginTime: '2020-04-20'
}
const invoicePager = await client.listInvoices(params)
console.log('Pager count:', await invoicePager.count())
let lastInvoice
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  lastInvoice = invoice
  if (total > 8) {
    console.log('Over the expected amount')
    break
  }
}
console.log(lastInvoice.createdAt)
```

Which outputs:
```
recurly v3.6.0
Pager count: 8
Over the expected amount
2020-04-18T21:14:52.000Z
```

However, if I pass `params.beginTime`, I would expect it not work, and the Pager count is null:
```javascript
console.log('recurly v' + require('recurly/package.json').version)
// In our sandbox account, we have 8 invoices that fit this criteria
const options = {
  params: {
    beginTime: '2020-04-20'
  }
}
const invoicePager = await client.listInvoices(options)
console.log('Pager count:', await invoicePager.count())
let lastInvoice
let total = 0
for await (const invoice of invoicePager.each()) {
  total += 1
  lastInvoice = invoice
  if (total > 8) {
    console.log('Over the expected amount')
    break
  }
}
console.log(lastInvoice.createdAt)
```

Which outputs:
```
recurly v3.6.0
Pager count: 8
Over the expected amount
2020-04-18T21:14:52.000Z
```

Is it something with how the API is being auto-generated?

**Comment by douglasmiller** [comment] 2020-04-21 20:33
Hey @geoffdutton, thank you for taking the time to collect this information and provide working code examples of the issues that you are experiencing. 

Essentially, you're reporting 3 different issues that you are encountering.

1. The `limit` parameter is not working in the way that you are expecting.
2. The `count()` method is returning `null` in certain requests.
3. The number of records that are returned when using the `beginTime` filter does not match the return value of the `count()` method.

The fourth example that you provided is essentially a duplicate of the `null` response on `count()` and too many records being returned.

The `limit` parameter is a constant source of confusion with regard to these `list_*` operations. Most people see the word limit and conclude that it will function like the limit keyword in a SQL query. However, in the case of the `list_*` operations, it is setting the number of records that will be returned in each API response that the `Pager` class makes. Higher values result in larger payloads, but fewer total API requests for large number of records.

The other two issues that you reported are legitimate bugs and I have identified the source of the issues and created a pull request to fix them.

Thank you again for providing a detailed bug report!

**Comment by douglasmiller** [comment] 2020-04-21 20:41
Ah, I forgot to explain the other two issues!

The `list_*` operations have a known issue where the expected `options` object does not match the function documentation or the non-`list_*` methods. Where all of the other operations in the library expect the options to be in the format `{ params: { paramName: 'param value' } }`, the `list_*` operations expect `{ paramName: 'param value' }`. This is ultimately a bug in the code and we only recently discovered that it existed. We are working on identifying a solution to fix the issue in a manner that does not break functionality for existing applications that use the node.js client library. 

When calling the `count()` method with the `{ params: { paramName: 'param value' } }` options, an error is returned from the API server that is not correctly caught by the client library. 

The case of returning more records than were identified by the `count()` response is a little trickier. The `Pager` class was dropping the query parameters and the following requests were returning all records.

**Closed** 2020-04-22 01:02 UTC
Labels: bug

**Comment by bhelx** [comment] 2020-04-22 01:05
@geoffdutton Apologies about the flaky Pager behavior. #106 is merged and in master. If you could try to load that directly and let us know if that works for you, that would be great. We can get a release out tomorrow or as soon as you're ready.
